Fix TestProvisionWithInvalidEkCert failure
--- FAIL: TestProvisionWithInvalidEkCert (4.06s)
provisioning_test.go:561: ProvisionTPM should have returned an error

The intention of the test is for it to temporarily modify the template used for
creating the endorsement key, but this fails in go 1.10 because the template
exported to the test is a copy of the one that ProvisionTPM uses.